version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    #container_name: app
    volumes:
      - .:/usr/app

    command: yarn dev-shell
    #ports:
    #  - '8001:8001'
